### ISSUE TITLE
Box86-64 + Wine co-exist

### ISSUE THREAD

**Issue by ThieuMinh26** [Ilya114/box86-termux#1]
# Install proot 
pkg update && pkg upgrade && 
termux-setup-storage && 
pkg install nano wget proot-distro pulseaudio && 
proot-distro install ubuntu &&
echo "pulseaudio --start --exit-idle-time=-1
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" >> ~/.bashrc &&
echo "proot-distro login ubuntu --shared-tmp" >> ~/.bashrc &&
cd /data/data/com.termux/files/usr/var/lib/proot-distro/dlcache &&
rm * &&
proot-distro login ubuntu --shared-tmp

# Install xfce + box86_64

wget https://raw.githubusercontent.com/ThieuMinh26/Proot-Setup/main/Proot-Distro.sh &&
chmod +x Proot-Distro.sh &&
./Proot-Distro.sh

wget https://raw.githubusercontent.com/ThieuMinh26/Proot-Setup/main/Box86-64_Wine86-64.sh && 
chmod +x Box86-64_Wine86-64.sh && 
./Box86-64_Wine86-64.sh

**Comment by wormstest** [comment]
If we will use multiarch, we need compile Turnip+Zink for armhf, you know how?

**Comment by ThieuMinh26** [comment]
> If we will use multiarch, we need compile Turnip+Zink for armhf, you know how?

its just matter of time

**Comment by ThieuMinh26** [comment]
should be enough

**Comment by Ilya114** [comment]
Multiarch will be use in guide
